### ISSUE TITLE
Error in messagelistener

### ISSUE THREAD

**Issue by jeffersantoss** [pluginsGLPI/telegrambot#10]
Description in log: Action completed, no processing required
Details inside item log Running status: Error. Telegram returned an invalid response! Please review your bot name and API key.

I tried with two different bot names and I'm totally sure that token and username are correct but I still the error.

![erro_glpi](https://user-images.githubusercontent.com/10839497/32010247-08ecd944-b990-11e7-9798-2816938ef8dc.JPG)

**Comment by marcelofares** [comment]
I have this same problem.
Did you solve it in what way?

**Comment by matrixsupport** [comment]
Me too has this Issue !

**Comment by newtonnh** [comment]
Me too, I already reinstalled my server about six times, but the problem is not solved. 

But I do not know if this will help anyone in any way, but there it goes:
If you followed GLPi setup guide probably you put as database password something like that something@something. I found on Internet a tip to edit manually the file config_db.php, verify the password, I don't know why, into file config_db.php the "at" appears something like that "%40", I've changed the "%40" for "@", to me the error on GLPi is solved, in my case I've configured to receive a message as a new ticket is open, but this function isn't work yet. I'm still looking for any tip to solve this problem.

Regards

**Comment by mays1509** [comment]
I also have that problem, I'm new to the tool, and this is solved?

**Comment by Drumhazzard** [comment]
Hi All!

I have the same error that @jeffersantoss 
I try with some differents bots, usernames and tokens, but the issue persits

:(

**Comment by Drumhazzard** [comment]
¡Solved!

In Windows clients, you need to modify 
...\plugins\telegrambot\vendor\longman\telegram-bot\src\Request.php

You must add 'verify' ==> false, at line 215

Like this: self::setClient(new Client(['base_uri' => self::$api_base_uri,'verify'   => false,]));

**Comment by jeffersantoss** [comment]
Where can I find this file @Drumhazzard ?

**Comment by LordBat** [comment]
Hi, any advance about this? i still have the same issue "Error. Telegram returned an invalid response! Please review your bot name and API key." 
I put the correct API key, and bot name.
i try to modify the "Request.php" but the problem continue.

This is my enviroment:

Ubuntu Server 16.04
php 7.0
mariaDB 10

any suggestion will be great. 

Thanks and Regards!

**Comment by yustas84** [comment]
Hello. We have same problem. tried all the above, the problem remains

**Comment by sazanof** [comment]
+++ Please help us!

**Comment by sazanof** [comment]
try this! its solved for me

....
'base_uri' => 'https://api.telegram.org',
'proxy'    => 'socks5://218.248.73.193:1080',
'verify'   => false,

**Comment by marcelofares** [comment]
The tip of our friend Drumhazzard solved it for me.

In Windows clients, you need to modify
... \ plugins \ telegrambot \ vendor \ longman \ telegram-bot \ src \ Request.php

You must add 'verify' ==> false, at line 215

Like this: self :: setClient (new Client (['base_uri' => self :: $ api_base_uri, 'verify' => false,]));

**Comment by yustas84** [comment]
This doesn't help too
self::setClient(new Client(['base_uri' => ' https://api.telegram.org ', 'proxy' => 'socks5: //218.248.73.193: 1080',  'verify' => false])); 
![image](https://user-images.githubusercontent.com/36289755/42201939-3252fa32-7eb3-11e8-9d2a-029c637e4dfd.png)

![image](https://user-images.githubusercontent.com/36289755/42201921-24af8526-7eb3-11e8-88ac-f6470c7f721b.png)

**Comment by sazanof** [comment]
Try this. Its worked for me
```
self::setClient(new Client(['base_uri' => self::$api_base_uri,'proxy'=>'socks5://yahaha.us:yahaha.us@socks5-a.yahaha.win:2019']));
```
if no ssl, then add 'verify' => false
